import { chmodSync, mkdirSync, writeFileSync, existsSync, unlinkSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import * as tmux from "./tmux.js";
import { shellEscapeSingleQuoted } from "./shell.js";

function quote(arg: string): string {
  return `'${shellEscapeSingleQuoted(arg)}'`;
}

const STATE_DIR = path.join(homedir(), ".config", "banyan", "state");

/**
 * Where banyan stashes the per-feature system prompt so the shell command
 * line stays short. The full prompt body lives on disk and is read at runtime
 * via `"$(cat <path>)"` — see the comment in `launchClaude` for why.
 */
export function featurePromptPath(projectName: string, feature: string): string {
  return path.join(STATE_DIR, `${projectName}.${feature}.prompt.md`);
}

export function deleteFeaturePrompt(projectName: string, feature: string): void {
  const p = featurePromptPath(projectName, feature);
  if (existsSync(p)) {
    try { unlinkSync(p); } catch { /* ignore */ }
  }
}

/**
 * Path to the per-feature launch script. We stash the full `claude … || claude …`
 * shell line in this script, then the tmux pane just runs `bash <script>` —
 * keeping the pane history clean (no 500-char command + `--add-dir 'path1' 'path2' …`
 * scrolling by before claude takes over).
 */
export function featureLaunchScriptPath(projectName: string, feature: string): string {
  return path.join(STATE_DIR, `${projectName}.${feature}.launch.sh`);
}

export function deleteFeatureLaunchScript(projectName: string, feature: string): void {
  const p = featureLaunchScriptPath(projectName, feature);
  if (existsSync(p)) {
    try { unlinkSync(p); } catch { /* ignore */ }
  }
}

/** Write a self-contained shell script that runs `body` and exec into the
 *  user's interactive shell when claude exits. Used by both feature agents
 *  and the orchestrator to keep the pane history readable. */
export function writeLaunchScript(scriptPath: string, body: string): void {
  mkdirSync(path.dirname(scriptPath), { recursive: true });
  const content = `#!/usr/bin/env bash
# Auto-generated by banyan. Safe to delete — banyan regenerates it on every
# launch / resume. Do not commit.
set +e
${body}
`;
  writeFileSync(scriptPath, content, "utf8");
  chmodSync(scriptPath, 0o700);
}

export interface LaunchClaudeOpts {
  /** Extra `--add-dir <path>` entries (sibling worktrees). */
  additionalDirs?: string[];
  /** First message sent to the agent on a fresh session (positional arg).
   *  Ignored on the `--continue` path so existing conversations aren't
   *  overwritten. */
  initialPrompt?: string;
  /** Text appended to claude's default system prompt via
   *  `--append-system-prompt`. Applied on both fresh and `--continue`
   *  sessions, on every turn.
   *
   *  When `projectName` + `feature` are provided, banyan writes the prompt
   *  to disk and the shell command does `"$(cat <path>)"` instead of inlining
   *  the (often huge) text. That keeps the tmux pane history clean — no more
   *  scrollback full of `cmdor quote>` continuation prompts. */
  systemPrompt?: string;
  /** Names used to derive the on-disk prompt file path. When omitted, falls
   *  back to inlining the system prompt as a quoted literal (legacy path).  */
  projectName?: string;
  feature?: string;
  /** Path to a JSON file passed via `claude --settings <path>`. Used by
   *  the autopilot driver to register a Stop hook that re-prompts the
   *  agent until the TODO list is done and a report has been submitted. */
  settingsPath?: string;
  /** Path to an MCP config JSON passed via `claude --mcp-config <path>`.
   *  Required for the agent to see banyan_* tools (finalize, report_done,
   *  set_todo, etc.). Without this, the agent runs naked and any system-
   *  prompt instruction to call a banyan_ tool becomes a no-op. */
  mcpConfig?: string;
  /** Stage the launch script on disk but do NOT touch the target pane.
   *  The caller (typically a bash script already inside the destination pane)
   *  is responsible for `exec bash <returned path>` to run claude. */
  stagedOnly?: boolean;
}

/**
 * Launch `claude` in the given tmux pane.
 *
 *   - `additionalDirs`: passed as `--add-dir` so a single Claude agent can
 *     reach across every worktree of the feature.
 *   - `systemPrompt`: appended via `--append-system-prompt`. This is how
 *     banyan installs its standing conventions (e.g. "call
 *     banyan_report_done when done") on every agent.
 *   - Resume: tries `claude --continue` first; on failure (no prior
 *     conversation for this cwd), falls back to a fresh session. The `||`
 *     in the shell handles this transparently — no error is shown thanks
 *     to stderr suppression on the first attempt.
 *   - `initialPrompt`: passed as a positional argument *only on the
 *     fresh-session fallback*. Ignored on `--continue`.
 */
export async function launchClaude(
  paneId: string,
  opts: LaunchClaudeOpts = {},
): Promise<{ launchScriptPath?: string }> {
  const dirs = opts.additionalDirs ?? [];
  const dirsTail =
    dirs.length > 0 ? ` --add-dir ${dirs.map(quote).join(" ")}` : "";

  // System prompt: prefer a file-backed indirection so the pane history
  // doesn't get spammed with a multi-thousand-character quoted literal.
  // The shell substitutes the file content at exec time via `"$(cat …)"`.
  let sysTail = "";
  if (opts.systemPrompt && opts.projectName && opts.feature) {
    mkdirSync(STATE_DIR, { recursive: true });
    const promptPath = featurePromptPath(opts.projectName, opts.feature);
    writeFileSync(promptPath, opts.systemPrompt, "utf8");
    sysTail = ` --append-system-prompt "$(cat ${quote(promptPath)})"`;
  } else if (opts.systemPrompt) {
    // Backward-compat: caller didn't pass project+feature → inline literal.
    sysTail = ` --append-system-prompt ${quote(opts.systemPrompt)}`;
  }

  const settingsTail = opts.settingsPath
    ? ` --settings ${quote(opts.settingsPath)}`
    : "";

  const mcpTail = opts.mcpConfig
    ? ` --mcp-config ${quote(opts.mcpConfig)}`
    : "";

  const sharedArgs = `${dirsTail}${mcpTail}${sysTail}${settingsTail}`;
  const freshArgs = opts.initialPrompt
    ? `${sharedArgs} ${quote(opts.initialPrompt)}`
    : sharedArgs;

  const claudeCmd = `claude --continue${sharedArgs} 2>/dev/null || claude${freshArgs}`;

  // Hide the verbose claude invocation behind a launch script when we know
  // where to put it (projectName + feature). The pane shows just one short
  // line; the full command lives on disk and is debuggable via `cat`.
  if (opts.projectName && opts.feature) {
    const scriptPath = featureLaunchScriptPath(opts.projectName, opts.feature);
    writeLaunchScript(scriptPath, claudeCmd);
    if (opts.stagedOnly) {
      // Caller will exec the script themselves — typically because banyan
      // is running INSIDE the target pane and would kill itself via respawn.
      return { launchScriptPath: scriptPath };
    }
    await tmux.sendKeys(paneId, `clear && bash ${quote(scriptPath)}`, { enter: true });
    return { launchScriptPath: scriptPath };
  }

  // Fallback: inline the full command (legacy callers without project/feature).
  if (opts.stagedOnly) {
    throw new Error("launchClaude: stagedOnly requires projectName + feature to know where to write the script");
  }
  await tmux.sendKeys(paneId, claudeCmd, { enter: true });
  return {};
}
